// Generated by https://quicktype.io

export interface Blog {
    id:               number;
    title:            string;
    description:      string;
    relation_details: RelationDetails;
}

export interface RelationDetails {
    data: Datum[];
}

export interface Datum {
    id:         number;
    attributes: DatumAttributes;
}

export interface DatumAttributes {
    title:               string;
    createdAt:           string;
    updatedAt:           string;
    publishedAt:         string;
    description_preview: string;
    editor:              string;
    uid:                 string;
    image:               Image;
}

export interface Image {
    data: ImageData;
}

export interface ImageData {
    id:         number;
    attributes: FluffyAttributes;
}

export interface FluffyAttributes {
    name:              string;
    alternativeText:   null;
    caption:           null;
    width:             number;
    height:            number;
    formats:           Formats;
    hash:              string;
    ext:               EXT;
    mime:              MIME;
    size:              number;
    url:               string;
    previewUrl:        null;
    provider:          Provider;
    provider_metadata: null;
    createdAt:         string;
    updatedAt:         string;
}

export enum EXT {
    JPEG = ".jpeg",
    Jpg = ".jpg",
}

export enum Provider {
    Local = "local",
}

export interface Formats {
    thumbnail: Large;
    small?:    Large;
    medium?:   Large;
    large?:    Large;
}

export interface Large {
    name:   string;
    hash:   string;
    ext:    EXT;
    mime:   MIME;
    path:   null;
    width:  number;
    height: number;
    size:   number;
    url:    string;
}

export enum MIME {
    ImageJPEG = "image/jpeg",
}
