// Generated by https://quicktype.io

export interface Response {
    data: ResponseData;
}

export interface ResponseData {
    id:         number;
    attributes: PurpleAttributes;
}

export interface PurpleAttributes {
    createdAt:   string;
    updatedAt:   string;
    publishedAt: string;
    components:  any[];
}

