// Generated by https://quicktype.io

export interface TeamList {
    id:          number;
    title:       string;
    worker:      Worker[];
}

export interface Worker {
    id:           number;
    name:         string;
    email:        string;
    presentation: string;
    image:        Image;
}

export interface Image {
    data: Data;
}

export interface Data {
    id:         number;
    attributes: Attributes;
}

export interface Attributes {
    name:              string;
    alternativeText:   null;
    caption:           null;
    width:             number;
    height:            number;
    formats:           Formats;
    hash:              string;
    ext:               EXT;
    mime:              MIME;
    size:              number;
    url:               string;
    previewUrl:        null;
    provider:          string;
    provider_metadata: null;
    createdAt:         string;
    updatedAt:         string;
}

export enum EXT {
    Jpg = ".jpg",
}

export interface Formats {
    thumbnail: Large;
    small:     Large;
    large?:    Large;
    medium:    Large;
}

export interface Large {
    name:   string;
    hash:   string;
    ext:    EXT;
    mime:   MIME;
    path:   null;
    width:  number;
    height: number;
    size:   number;
    url:    string;
}

export enum MIME {
    ImageJPEG = "image/jpeg",
}
